// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQiHnoOYKEDq8fQdArg5zQ3TxRo_l8Io',
    appId: '1:463750892188:android:e38d65017390da73373b59',
    messagingSenderId: '463750892188',
    projectId: 'cercle-mystic',
    storageBucket: 'cercle-mystic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuswfFiseC05xEHv6oyV3MhKDvMSGYqkc',
    appId: '1:463750892188:ios:6f8c597dc3ca5ed4373b59',
    messagingSenderId: '463750892188',
    projectId: 'cercle-mystic',
    storageBucket: 'cercle-mystic.firebasestorage.app',
    iosClientId: '463750892188-nfu3vrmar4jlsqbcsn5sea5lco78mknm.apps.googleusercontent.com',
    iosBundleId: 'com.game.mystic',
  );
}
